# Generated by Django 4.2.30 on 2026-06-30 10:03

import core.fields
import core.models.base_mutation
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import training.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_exportablequerymodel_create_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTrainingSession',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_token', models.CharField(db_index=True, default=training.models.generate_registration_token, max_length=64)),
                ('registration_open', models.BooleanField(default=False)),
                ('registration_opens_at', core.fields.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', core.fields.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical training session',
                'verbose_name_plural': 'historical training sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_token', models.CharField(default=training.models.generate_registration_token, max_length=64, unique=True)),
                ('registration_open', models.BooleanField(default=False)),
                ('registration_opens_at', core.fields.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', core.fields.DateTimeField(blank=True, null=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingSessionMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.AddField(
            model_name='historicaltrainingparticipant',
            name='check_in_method',
            field=models.CharField(choices=[('MANUAL', 'Manual entry'), ('QR', 'QR self check-in')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltrainingparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrainingparticipant',
            name='registered_at',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrainingparticipant',
            name='self_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='check_in_method',
            field=models.CharField(choices=[('MANUAL', 'Manual entry'), ('QR', 'QR self check-in')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='registered_at',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='self_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsessionmutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_sessions', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='trainingsessionmutation',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='training.training'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='training',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.training'),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrainingparticipant',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='training.trainingsession'),
        ),
        migrations.AddIndex(
            model_name='trainingparticipant',
            index=models.Index(fields=['session'], name='training_tr_session_bf4302_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingparticipant',
            index=models.Index(fields=['self_registered'], name='training_tr_self_re_cbef04_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['training'], name='training_tr_trainin_5fdc47_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['registration_open'], name='training_tr_registr_889583_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['session_date'], name='training_tr_session_9d8451_idx'),
        ),
    ]
