# Generated by Django 4.2.30 on 2026-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_historicaltrainingsession_trainingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraining',
            name='intended_for',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='intended_for',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
