# Generated by Django 4.2.30 on 2026-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainer_code_sequence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainingparticipant',
            index=models.Index(fields=['gender'], name='training_tr_gender_34a1f4_idx'),
        ),
    ]
