# Generated by Django 4.2.30 on 2026-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingparticipant_training_tr_gender_34a1f4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrainingparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainingparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
