# Generated by Django 4.2.30 on 2026-08-05 07:07

import core.fields
import core.models.base_mutation
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_alter_exportablequerymodel_create_date_and_more'),
        ('training', '0012_job_title_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTrainingLevel',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('implementation_location', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_application', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical training level',
                'verbose_name_plural': 'historical training levels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('implementation_location', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_application', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingLevelMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.AddField(
            model_name='traininglevelmutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_levels', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='traininglevelmutation',
            name='training_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='training.traininglevel'),
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='facilitator_categories',
            field=models.ManyToManyField(blank=True, related_name='facilitator_for_levels', to='training.participantcategory'),
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='primary_categories',
            field=models.ManyToManyField(blank=True, related_name='primary_for_levels', to='training.participantcategory'),
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraininglevel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraininglevel',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraininglevel',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltraining',
            name='level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.traininglevel'),
        ),
        migrations.AddField(
            model_name='training',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainings', to='training.traininglevel'),
        ),
        migrations.AddIndex(
            model_name='traininglevel',
            index=models.Index(fields=['code'], name='training_tr_code_656d40_idx'),
        ),
        migrations.AddIndex(
            model_name='traininglevel',
            index=models.Index(fields=['sequence'], name='training_tr_sequenc_01189c_idx'),
        ),
        migrations.AddIndex(
            model_name='traininglevel',
            index=models.Index(fields=['is_active'], name='training_tr_is_acti_b2fa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['level'], name='training_tr_level_i_70fa7d_idx'),
        ),
    ]
